spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #检测连接是否有效的sql
    validationQuery: select 'x'
    validationQueryTimeout: 60000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:
#    pool:
#      max-active: 8
#      max-wait: 1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0
  #redis 集群配置
#  redis:
#    cluster:
#      nodes:
#        - 192.168.2.119:6369
#  devtools:
#    restart:
#      #热部署生效
#      enabled: true
#      #设置重启的目录
#      #additional-paths: src/main/java
#      #classpath目录下的WEB-INF文件夹内容修改不重启
#      exclude: WEB-INF/**
#  kafka:
#    #指定kafka 代理地址，可以多个
#    bootstrap-servers: 192.168.2.119:9092
#    template:
#      #指定默认topic id
#      default-topic: default-topic
#    listener:
#      #指定listener 容器中的线程数，用于提高并发量
#      concurrency: 3
#    consumer:
#      #指定默认消费者group id
#      group-id: defGroupId
#      #key-value序列化反序列化
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      #key-value序列化反序列化
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      #每次批量发送消息的数量
#      batch-size: 1000

#logging:
#  level: debug
#  file: logs/kok_ssp_lite_logging.log

mybatis:
  #entity扫描的包名
  type-aliases-package: com.smart.ssp.lite.model
  #Mapper.xml所在的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #别名配置
  config-location: classpath:mybatis/mybatis-config.xml

#通用mapper配置
#mapper:
#    mappers:
#        - com.smartsp.lite.mapper
#    not-empty: false
#    identity: MYSQL

#mybatis分页配置
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql